### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by creydr**
Fixing some dependency issues after https://github.com/knative/eventing/pull/7328 merged.

Dependency update: 557f556afae452fa06e8f9edee0497a6d9899b96
Fixing build issues: 4182d97b0086c9469516f5c9f0abac724f8ce8d5
Fixing unit test (need to have a kubeclient on the context): a8a52e22da820284ff08786effe6ea0b30380516

### CODE REVIEW

**Review by gabo1208 — APPROVED** [review]

**Comment by creydr** [comment]
@gabo1208 I am not really in rabbitmq. Just tried to fix some dependency issues. Can you tell, whats wrong on the e2e tests?

**Comment by gabo1208** [comment]
> @gabo1208 I am not really in rabbitmq. Just tried to fix some dependency issues. Can you tell, whats wrong on the e2e tests?

Sure I can check a bit later today

**Comment by gabo1208** [comment]
It's giving me the following error: `"Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context"`. I'm trying to solve it today but let me know if you now how

**Comment by creydr** [comment]
@gabo1208 in c037e4bf8d8f01f301eaeb1b9dfb18e07c475a5f I pass a context now to the adapter with configured clients.
We can also think about adding this to `adapter.MainMessageAdapterWithContext`, similar as done for `adapter.Main()`:

https://github.com/knative-extensions/eventing-rabbitmq/blob/f7a0e504cc34178a131c2444db1a2005da316f79/vendor/knative.dev/eventing/pkg/adapter/v2/main.go#L141-L147 

and then configure it receiver_main via something like 
```
func main() {
	ctx := signals.NewContext()
	ctx = adapter.WithInjectorEnabled(ctx)
	adapter.MainMessageAdapterWithContext(ctx, "rabbitmqsource", kadapter.NewEnvConfig, kadapter.NewAdapter)
}
```

**Comment by gabo1208** [comment]
> @gabo1208 in [c037e4b](https://github.com/knative-extensions/eventing-rabbitmq/commit/c037e4bf8d8f01f301eaeb1b9dfb18e07c475a5f) I pass a context now to the adapter with configured clients. We can also think about adding this to `adapter.MainMessageAdapterWithContext`, similar as done for `adapter.Main()`:
> 
> https://github.com/knative-extensions/eventing-rabbitmq/blob/f7a0e504cc34178a131c2444db1a2005da316f79/vendor/knative.dev/eventing/pkg/adapter/v2/main.go#L141-L147
> 
> and then configure it receiver_main via something like
> 
> ```
> func main() {
> 	ctx := signals.NewContext()
> 	ctx = adapter.WithInjectorEnabled(ctx)
> 	adapter.MainMessageAdapterWithContext(ctx, "rabbitmqsource", kadapter.NewEnvConfig, kadapter.NewAdapter)
> }
> ```

would be nice if you can create an issue for that so it doesn't get lost on this PR :)

Thank you very much for the help with this PR!

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
