### PR TITLE
Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by creydr**
Same as #1448 but bumps controller-runtime from 0.14 to 0.19 to fix build issues (`Error: vendor/sigs.k8s.io/controller-runtime/pkg/metrics/leaderelection.go:26:71: undefined: leaderelection.SwitchMetric`)

/assign @ikavgo

### CODE REVIEW

**Comment by ikavgo** [comment]
/approve

@creydr Thank you, can I then just close #1448?

**Comment by creydr** [comment]
> /approve
> 
> @creydr Thank you, can I then just close #1448?

Hey @ikavgo ,
#1448 can be closed. Otherwise it will be updated again, after this PR merged (as I guess there are some new changes since this PR was created)

**Pull request merged**
